In [188]:
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import time

In [297]:
categories = ["CB", "C0", "C1", "C2"]
category_dict = {"CB" : [" CВ", " CB", " СВ", " СB"], "C0" : [" CO", " C0", " С0", " СО", " CО", " СO"], "C1" : [" C1", " С1"], "C2" :[" C2", " С2"]}

In [317]:
def get_category(name : str):
    for category in category_dict:
        for spelling in category_dict[category]:
            if spelling in name:
                return category
    return None

In [98]:
driver = webdriver.Chrome()
driver.get("https://5ka.ru/search/?value=яйца")
time.sleep(5)
actions = ActionChains(driver)
actions.send_keys(Keys.END).perform()
time.sleep(5)
actions.send_keys(Keys.END).perform()
goods = driver.find_elements(By.CLASS_NAME, "chakra-stack.KnkuqE3h-.HmedBAdm-.css-8g8ihq")

In [103]:
names = []
prices = []
for good in goods:
    name = good.find_element(By.CLASS_NAME, "chakra-text.SdLEFc2B-.css-1jdqp4k").text
    price_rub = int(good.find_element(By.CLASS_NAME, "chakra-text.DUXYWqnZ-.css-6uvdux").text)
    price_kop = int(good.find_element(By.CLASS_NAME, "chakra-text.j2bifgeA-.css-6uvdux").text)
    price = price_rub + price_kop / 100
    names.append(name)
    prices.append(price)

In [119]:
raw_eggs_data_dict = dict(zip(names, prices))

In [170]:
eggs_data_dict = {
    'Название': [],
    'Категория': [],
    'Цена': []
}

pyaterka = pd.DataFrame(eggs_data_dict)

In [172]:
categories = ['СВ', 'СО', 'С0', 'С1', 'С2']
for name in raw_eggs_data_dict:
    for category in categories:
        if category in name:
            new_row = pd.DataFrame({"Название" : [name], "Категория" : [category], "Цена" : [raw_eggs_data_dict[name]]})
            pyaterka = pd.concat([pyaterka, new_row], ignore_index = True)
            break

In [176]:
pyaterka['Категория'] = pd.Categorical(pyaterka['Категория'], categories=categories, ordered=True)

# Сортируем DataFrame по колонке "Категория"
pyaterka = pyaterka.sort_values('Категория')
pyaterka = pyaterka.reset_index(drop = True)

In [178]:
pyaterka

                                             Название Категория    Цена
0                        Яйцо Окское СВ столовое 10шт        СВ  179.99
1               Яйцо куриное Окское столовое СО 10шт.        СО  145.59
2                 Яйцо куриное Роскар Экстра СО 10шт.        СО  139.99
3                 Яйцо куриное Лето столовое СО 10шт.        СО  139.99
4        Яйца Село Зеленое Деревенские куриные СО 6шт        СО   99.99
5   Яйца Вкус & Польза Активита куриные пищевые ст...        С1  129.99
6               Яйцо куриное Окское столовое С1 10шт.        С1  109.99
7      Яйцо куриное Село Зеленое Деревенское С1 10шт.        С1  119.99
8                          Яйцо куриное Лето С1 20шт.        С1  234.99
9                  Яйцо куриное Лето пищевое С1 10шт.        С1  119.99
10                Яйцо куриное Волжанин С1 белое 10шт        С1  119.99
11  Яйца Село Зеленое Деревенские куриное пищевое ...        С1  189.99
12                      Яйцо Окское столовое С2 10шт.        С2  100.79

In [184]:
pyaterka['Количество яиц в упаковке'] = pyaterka['Название'].str.extract(r'(\d+)шт')
pyaterka['Количество яиц в упаковке'] = pd.to_numeric(pyaterka['Количество яиц в упаковке'])
pyaterka['Цена одного яйца'] = pyaterka['Цена'] / pyaterka['Количество яиц в упаковке']

In [186]:
pyaterka

,Название,Категория,Цена,Количество яиц в упаковке,Цена одного яйца
0,Яйцо Окское СВ столовое 10шт,СВ,179.99,10,17.9990
1,Яйцо куриное Окское столовое СО 10шт.,СО,145.59,10,14.5590
2,Яйцо куриное Роскар Экстра СО 10шт.,СО,139.99,10,13.9990
3,Яйцо куриное Лето столовое СО 10шт.,СО,139.99,10,13.9990
4,Яйца Село Зеленое Деревенские куриные СО 6шт,СО,99.99,6,16.6650
5,Яйца Вкус & Польза Активита куриные пищевые ст...,С1,129.99,10,12.9990
6,Яйцо куриное Окское столовое С1 10шт.,С1,109.99,10,10.9990
7,Яйцо куриное Село Зеленое Деревенское С1 10шт.,С1,119.99,10,11.9990
8,Яйцо куриное Лето С1 20шт.,С1,234.99,20,11.7495
9,Яйцо куриное Лето пищевое С1 10шт.,С1,119.99,10,11.9990
10,Яйцо куриное Волжанин С1 белое 10шт,С1,119.99,10,11.9990
11,Яйца Село Зеленое Деревенские куриное пищевое ...,С1,189.99,15,12.6660
12,Яйцо Окское столовое С2 10шт.,С2,100.79,10,10.0790

In [319]:
driver = webdriver.Chrome()
driver.get("https://www.perekrestok.ru/cat/search?search=яйца")
time.sleep(5)
actions = ActionChains(driver)
actions.send_keys(Keys.END).perform()
time.sleep(5)
actions.send_keys(Keys.END).perform()
goods = driver.find_elements(By.CLASS_NAME, "chakra-stack.KnkuqE3h-.HmedBAdm-.css-8g8ihq")

In [320]:
goods = driver.find_elements(By.CLASS_NAME, "product-card__content")

In [321]:
names = []
prices = []
for good in goods:
    name = good.find_element(By.CLASS_NAME, "product-card__title").text
    price_raw = good.find_element(By.CLASS_NAME, "price-new")
    price = float(price_raw.text.split('\n')[1][:-2].replace(',', '.'))
    names.append(name)
    prices.append(price)

In [322]:
raw_eggs_data_dict = dict(zip(names, prices))

In [323]:
eggs_data_dict = {
    'Название': [],
    'Категория': [],
    'Цена': []
}

perek = pd.DataFrame(eggs_data_dict)

In [324]:
for name in raw_eggs_data_dict:
    category = get_category(name)
    if category:
        new_row = pd.DataFrame({"Название" : [name], "Категория" : [category], "Цена" : [raw_eggs_data_dict[name]]})
        perek = pd.concat([perek, new_row], ignore_index = True)

In [325]:
perek['Категория'] = pd.Categorical(perek['Категория'], categories=categories, ordered=True)

# Сортируем DataFrame по колонке "Категория"
perek = perek.sort_values('Категория')
perek = perek.reset_index(drop = True)

In [326]:
perek['Количество яиц в упаковке'] = perek['Название'].str.extract(r'(\d+)шт')
perek['Количество яиц в упаковке'] = pd.to_numeric(perek['Количество яиц в упаковке'])
perek['Цена одного яйца'] = perek['Цена'] / perek['Количество яиц в упаковке']

In [327]:
perek

,Название,Категория,Цена,Количество яиц в упаковке,Цена одного яйца
0,Яйцо куриное Окское мытое дезинфицированное СВ...,CB,159.99,10,15.999000
1,Яйцо куриное пищевое столовое СО Маркет Перекр...,C0,124.99,10,12.499000
2,"Яйцо Окское столовое СО, 10шт",C0,139.99,10,13.999000
3,"Яйцо куриное Роскар Экстра СО, 10шт",C0,149.99,10,14.999000
4,"Яйцо куриное Лето пищевое столовое СО, 10шт",C0,139.99,10,13.999000
5,Яйца Село Зелёное Деревенские куриные пищевые ...,C0,299.99,20,14.999500
6,"Яйца Суздальское куриные С0, 10шт",C0,144.99,10,14.499000
7,"Яйцо куриное Фёдоровская ПФ С0, 9шт",C0,199.99,9,22.221111
8,"Яйцо куриное С1 Пр!ст, 10шт",C1,93.99,10,9.399000
9,"Яйцо куриное столовое С1 Маркет Перекрёсток, 10шт",C1,109.99,10,10.999000
10,Яйцо куриное активита С1 с селеном и йодом Зел...,C1,124.99,10,12.499000
11,"Яйцо куриное Окское столовое С1, 10шт",C1,124.99,10,12.499000
12,"Яйцо куриное Лето С1, 20шт",C1,249.99,20,12.499500
13,"Яйцо Село Зеленое Деревенское С1, 10шт",C1,129.99,10,12.999000
14,"Яйцо куриное Окское столовое С2, 10шт",C2,95.99,10,9.599000

In [259]:
for good in goods:
    name = good.find_element(By.CLASS_NAME, "product-card__title").text
    price_raw = good.find_element(By.CLASS_NAME, "price-new")
    price = float(price_raw.text.split('\n')[1][:-2].replace(',', '.'))
    names.append(name)
    prices.append(price)

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=134.0.6998.89)
Stacktrace:
	GetHandleVerifier [0x00007FF741D8FE45+26629]
	(No symbol) [0x00007FF741CF6010]
	(No symbol) [0x00007FF741B8931A]
	(No symbol) [0x00007FF741B74F65]
	(No symbol) [0x00007FF741B99E04]
	(No symbol) [0x00007FF741C0F85F]
	(No symbol) [0x00007FF741C2FA55]
	(No symbol) [0x00007FF741C07883]
	(No symbol) [0x00007FF741BD0550]
	(No symbol) [0x00007FF741BD1803]
	GetHandleVerifier [0x00007FF7420E72BD+3529853]
	GetHandleVerifier [0x00007FF7420FDA22+3621858]
	GetHandleVerifier [0x00007FF7420F24D3+3575443]
	GetHandleVerifier [0x00007FF741E5B77A+860474]
	(No symbol) [0x00007FF741D0088F]
	(No symbol) [0x00007FF741CFCBC4]
	(No symbol) [0x00007FF741CFCD66]
	(No symbol) [0x00007FF741CEC2C9]
	BaseThreadInitThunk [0x00007FF94E05E8D7+23]
	RtlUserThreadStart [0x00007FF94ECDBF6C+44]