In [29]:
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import time
import requests

In [31]:
driver = webdriver.Chrome()
names = []
prices = []
for page in range(1, 8):
    driver.get(f"https://www.agrosadovod.ru/catalog/korma-dlya-ptits/kury/nesushek/page/{page}/")
    names_list = driver.find_elements(By.CLASS_NAME, "product-loop-title")
    price_list = driver.find_elements(By.CLASS_NAME, "price")
    names = names + [name.text for name in names_list]
    prices = prices + [int(price.text.split()[-2]) for price in price_list]

In [32]:
d = dict(zip(names, prices))

In [33]:
keys = []
for name in d:
    if any(st in name for st in ["СМЕСЬ", "КОМБИКОРМ"]):
        keys.append(name)

In [34]:
df = pd.DataFrame({"Название" : keys, "Цена" : [d[key] for key in keys]})

In [35]:
df['КГ в мешке'] = df['Название'].str.extract(r'(\d+) КГ')
df['КГ в мешке'] = pd.to_numeric(df['КГ в мешке'])
df.dropna(inplace = True)
df["Цена за КГ"] = df["Цена"] / df["КГ в мешке"]

In [36]:
df

,Название,Цена,КГ в мешке,Цена за КГ
0,ЗЕРНОСМЕСЬ ДЛЯ ПТИЦ 7 ВИДОВ ЗЕРНА (МЕШОК 25 КГ),1100,25.0,44.000000
1,КОМБИКОРМ ПК-1 ДЛЯ КУР-НЕСУШЕК (МЕШОК 30 КГ) «...,1500,30.0,50.000000
2,ЗЕРНОСМЕСЬ ДЛЯ ПТИЦ ЭЛИТА (МЕШОК 25 КГ),1300,25.0,52.000000
3,"КОМБИКОРМ ПК-6 ДЛЯ БРОЙЛЕРОВ, КУР, ГУСЕЙ СТАРШ...",1700,30.0,56.666667
4,КОМБИКОРМ ПК-5 «СТАРТ» ДЛЯ МОЛОДНЯКА ПТИЦ (МЕШ...,2200,30.0,73.333333
5,ЗЕРНОСМЕСЬ ДЛЯ ПТИЦ №4 (МЕШОК 25 КГ),1000,25.0,40.000000
6,КОМБИКОРМ ПК-4 ДЛЯ МОЛОДНЯКА ПТИЦЫ (МЕШОК 30 К...,1600,30.0,53.333333
7,КОМБИКОРМ “СОЛНЫШКО” ДЛЯ ЦЫПЛЯТ (МЕШОК 10 КГ),1200,10.0,120.000000
9,КОМБИКОРМ (КОРМОСМЕСЬ) УНИВЕРСАЛЬНЫЙ ГРАНУЛИРО...,1300,30.0,43.333333
10,КОМБИКОРМ ПК-5 «ПРЕДСТАРТ» ДЛЯ МОЛОДНЯКА ПТИЦ ...,2000,30.0,66.666667

In [47]:
options = webdriver.ChromeOptions()
# подгружаем UserAgent своего браузера, чтобы обойти защиту Ozon от ботов
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36")
# подгружаем профиль своего браузера, чтобы обойти защиту Ozon от ботов
options.add_argument(r"user-data-dir=C:\Users\Yaroslav\AppData\Local\Google\Chrome\User Data")  
options.add_argument('--profile-directory=Default')
driver = webdriver.Chrome(options=options)
actions = ActionChains(driver)
i = 2
url = f'https://www.ozon.ru/category/kombikorm-dlya-kur-nesushek/?page={1+4*i}&search_page_state=fDTeLRzirH_QScT9xHj04E-mPR822Or9HsRbpPNYt4yNMFH13pr6hyUrjoDLEES9s06f8rEN_8oQNI-8VZeOj60JuuKoog3v-xadvP1ncPFQwTEATdFvBLzEtL3LvP1WdHXqyrb5O1eNCvwrmku6U22fnhDQmlI22EJqcIrn-5JmgwMsSTkaWNCk5j4gNJ5Qmqu38_PYSX027K-RDp69C-OlDPPGQFjz4tQ3HPW-Uyk-k342t77g-rEyEWGGGG5F9mBd9w5w30twT7s0_T_5UQr2IkHBtidJDOCKpfn48V5k3VaaRSrRKav67fFwREf_MZey_xJhhIBqfHngM3mkTBRKBiAK6dvHi-kxXMXl2ZjHZ4G7g7R3Fs2rDxsGBpHmnkJKRdOvUeMT4W2kD6GT7sNOwrzRZg%3D%3D'
driver.get(url)
time.sleep(5)
actions.send_keys(Keys.END).perform()
time.sleep(5)
actions.send_keys(Keys.END).perform()
time.sleep(5)
actions.send_keys(Keys.END).perform()
print(len(driver.find_elements(By.CLASS_NAME, "jm2_25.m2j_25.tile-root")))

48

In [252]:
options = webdriver.ChromeOptions()
# подгружаем UserAgent своего браузера, чтобы обойти защиту Ozon от ботов
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36")
# подгружаем профиль своего браузера, чтобы обойти защиту Ozon от ботов
options.add_argument(r"user-data-dir=C:\Users\Yaroslav\AppData\Local\Google\Chrome\User Data")  
options.add_argument('--profile-directory=Default')
driver = webdriver.Chrome(options=options)
actions = ActionChains(driver)
prices = []
names = []
for i in range(8):
    url = f'https://www.ozon.ru/category/kombikorm-dlya-kur-nesushek/?page={1+4*i}&search_page_state=fDTeLRzirH_QScT9xHj04E-mPR822Or9HsRbpPNYt4yNMFH13pr6hyUrjoDLEES9s06f8rEN_8oQNI-8VZeOj60JuuKoog3v-xadvP1ncPFQwTEATdFvBLzEtL3LvP1WdHXqyrb5O1eNCvwrmku6U22fnhDQmlI22EJqcIrn-5JmgwMsSTkaWNCk5j4gNJ5Qmqu38_PYSX027K-RDp69C-OlDPPGQFjz4tQ3HPW-Uyk-k342t77g-rEyEWGGGG5F9mBd9w5w30twT7s0_T_5UQr2IkHBtidJDOCKpfn48V5k3VaaRSrRKav67fFwREf_MZey_xJhhIBqfHngM3mkTBRKBiAK6dvHi-kxXMXl2ZjHZ4G7g7R3Fs2rDxsGBpHmnkJKRdOvUeMT4W2kD6GT7sNOwrzRZg%3D%3D'
    driver.get(url)
    time.sleep(3)
    actions.send_keys(Keys.END).perform()
    time.sleep(3)
    actions.send_keys(Keys.END).perform()
    time.sleep(3)
    actions.send_keys(Keys.END).perform()
    goods = driver.find_elements(By.CLASS_NAME, "jm2_25.m2j_25.tile-root")
    nms = [good.find_element(By.CLASS_NAME, "tsBody500Medium") for good in goods]
    prcs = [int(''.join(good.find_element(By.CLASS_NAME, "c3025-a1.tsHeadline500Medium.c3025-b1.c3025-a6").text.split()[:-1])) for good in goods]
    names += [name.text for name in nms]
    prices += prcs

In [253]:
d = dict(zip(names, prices))

In [254]:
stop_words = ['добавк', 'витамин']
cont_words = ['комбикорм', 'смес']
names_to_save = []
for name in d:
    if any(st in name.lower() for st in cont_words) and not any(st in name.lower() for st in stop_words) and ('кг' in name.lower()):
        names_to_save.append(name)

In [262]:
df = pd.DataFrame({"Название" : names_to_save, "Цена" : [d[key] for key in names_to_save]})
df['КГ в мешке'] = df['Название'].str.extract(r'(\d+) кг')
df

                                              Название  Цена КГ в мешке
0    Комбикорм для кур несушек "Ряба" (Несушка прод...  1431         20
1          Комбикорм для кур Несушек 20-45 недель, 5кг   435        NaN
2         Комбикорм для кур Несушек 20-45 недель, 10кг   703        NaN
3    Комбикорм для кур несушек "Ряба" (Несушка прод...   782         10
4                      Комбикорм для кур несушек 25 кг  1200         25
..                                                 ...   ...        ...
162  Комбикорм для цыплят от 0 Старт 25кг, Глазовск...  2001        NaN
163  Комбикорм Финиш- Н для несушек цыплят, утят, г...  1001         10
164  Комбикорм для кур несушек 15 кг Кладка LAYER, ...  1261         15
165  Комбикорм для цыплят бройлеров ФИНИШ 25 кг ПК ...  1773         25
166  Комбикорм для цыплят, утят, гусят, перепелят о...  1253        NaN

[167 rows x 3 columns]

In [123]:
goods[0]

In [124]:
goods[0].find_elements(By.CLASS_NAME, 'tsBody500Medium')

In [7]:
len(driver.find_elements(By.CLASS_NAME, "j1m_25.jm2_25.tile-root"))

0

In [285]:
driver.find_elements(By.CLASS_NAME, "j1m_25.jm2_25.tile-root")

[]

In [283]:
driver.find_elements(By.CLASS_NAME, "j1m_25.jm2_25.tile-root")

[]

AttributeError: 'WebDriver' object has no attribute 'text'